import slots as slots
slots.OneThousandLakesStudios
# slotTotal = [
#         '0xedge-wild-zeus',
#         '0xedgefrutti-bonanza',
#         '0xedge-super-candy-drop',
#         '0xedge-do-not-redeem-it',
#         '0xedge-5-alpha-planets',
#         '1000lakesstudios-toivo',
#         '1000lakesstudios-disco-cubes',
#         '1000lakesstudios-bass-fury',
#         '1000lakesstudios-operation-epic-taco',
#         '1000lakesstudios-r-i-p-1000',
#         '1000lakesstudios-flying-finns-1000',
#         '1000lakesstudios-bloom-em',
#         '1000lakesstudios-apex-syndicate',
#         '1000lakesstudios-yakuza-v-i-p',
#         '1000lakesstudios-candy-carnival-spring-spritz'
# ]

override = True
overrideName = '18gaming-toppings-tantalizer'

def findSubclass(sb, slotName, obs):
        if override:
                slotName = overrideName     # override
        match slotName:
                case '0xedge-wild-zeus':
                        return slots.ZeroxEdge.WildZeus(sb,obs)
                case '0xedgefrutti-bonanza':
                        return slots.ZeroxEdge.FruttiBonanza(sb,obs)
                case '0xedge-super-candy-drop':
                        return slots.ZeroxEdge.SuperCandyDrop(sb,obs)
                case '0xedge-do-not-redeem-it':
                        return slots.ZeroxEdge.DoNotRedeemIt(sb,obs)
                case '0xedge-5-alpha-planets':
                        return slots.ZeroxEdge.FiveAlphaPlanets(sb,obs)
                case '0xluckylab-obsidian-spin':
                        return slots.ZeroxLuckyLab.ObsidianSpin(sb,obs)
                case '1000lakesstudios-toivo':
                        return slots.OneThousandLakesStudios.Toivo(sb,obs)
                case '1000lakesstudios-disco-cubes':
                        return slots.OneThousandLakesStudios.DiscoCubes(sb,obs)
                case '1000lakesstudios-bass-fury':
                        return slots.OneThousandLakesStudios.BassFury(sb,obs)
                case '1000lakesstudios-operation-epic-taco':
                        return slots.OneThousandLakesStudios.OperationEpicTaco(sb,obs)
                case '1000lakesstudios-r-i-p-1000':
                        return slots.OneThousandLakesStudios.RIPOneThousand(sb,obs)
                case '1000lakesstudios-flying-finns-1000':
                        return slots.OneThousandLakesStudios.FlyingFinsOneThousand(sb,obs)
                case '1000lakesstudios-bloom-em':
                        return slots.OneThousandLakesStudios.BloomEm(sb,obs)
                case '1000lakesstudios-apex-syndicate':
                        return slots.OneThousandLakesStudios.ApexSyndicate(sb,obs)
                case '1000lakesstudios-yakuza-v-i-p':
                        return slots.OneThousandLakesStudios.YakuzaVIP(sb,obs)
                case '1000lakesstudios-candy-carnival-spring-spritz':
                        return slots.OneThousandLakesStudios.CandyCarnivalSpringSpritz(sb,obs)
                case '1000lakesstudios-twisted-candy-shop':
                        return slots.OneThousandLakesStudios.TwistedCandyShop(sb,obs)
                case '1000lakesstudios-arctic-runes':
                        return slots.OneThousandLakesStudios.ArcticRunes(sb,obs)
                case '1000lakes-rotation-of-ra':
                        return slots.OneThousandLakes.RotationOfRa(sb,obs)
                case '111lightproductions-the-syndicate':
                        return slots.OneThousandOneHundredElevenLightProductions.TheSyndicate(sb,obs)
                case '111lightproductions-gemburst-rush':
                        return slots.OneThousandOneHundredElevenLightProductions.GemburstRush(sb,obs)
                case '111lightproductions-nfl-touchdown':
                        return slots.OneThousandOneHundredElevenLightProductions.NFLTouchdown(sb,obs)
                case '111lightproductions-dragon-fortunes':
                        return slots.OneThousandOneHundredElevenLightProductions.DragonFortunes(sb,obs)
                case '111lightproductions-legends-of-the-lost-grove':
                        return slots.OneThousandOneHundredElevenLightProductions.LegendsOfTheLostGrove(sb,obs)
                case '111lightproductions-hearts-in-sync':
                        return slots.OneThousandOneHundredElevenLightProductions.HeartsInSync(sb,obs)
                case '111lightproductions-sunset-serenade':
                        return slots.OneThousandOneHundredElevenLightProductions.SunsetSerenade(sb,obs)
                case '1789studios-cat-war':
                        return slots.OneThousandSevenHundredEightyNineStudios.CatWar(sb,obs)
                case '18gaming-sweet-stake-25k':
                        return slots.EighteenGaming.SweetStakeTwentyFiveK(sb,obs)
                case '18gaming-bowling-riches':
                        return slots.EighteenGaming.BowlingRiches(sb,obs)
                case '18gaming-golden-piggy':
                        return slots.EighteenGaming.GoldenPiggy(sb,obs)
                case '18gaming-rock-n-roll':
                        return slots.EighteenGaming.RockNRoll(sb,obs)
                case '18gaming-buffalo-blaze-2':
                        return slots.EighteenGaming.BuffaloBlazeTwo(sb,obs)
                case '18gaming-mystical-plum-grove':
                        return slots.EighteenGaming.MysticalPlumGrove(sb,obs)
                case '18gaming-aztec-sun-blaze':
                        return slots.EighteenGaming.AztecSunBlaze(sb,obs)
                case '18gaming-wrath-of-olympus':
                        return slots.EighteenGaming.WrathOfOlympus(sb,obs)
                case '18gaming-crypto-bonanza':
                        return slots.EighteenGaming.CryptoBonanza(sb,obs)
                case '18gaming-dragon-fortune':
                        return slots.EighteenGaming.DragonFortune(sb,obs)
                case '18gaming-sheriffs-bounty':
                        return slots.EighteenGaming.SheriffsBounty(sb,obs)
                case '18gaming-wall-street-honey-stakes':
                        return slots.EighteenGaming.WallStreetHoneyStakes(sb,obs)
                case '18gaming-buffalo-blaze':
                        return slots.EighteenGaming.BuffaloBlaze(sb,obs)
                case '18gaming-derby-race':
                        return slots.EighteenGaming.DerbyRace(sb,obs)
                case '18gaming-beachside-betties':
                        return slots.EighteenGaming.BeachsideBetties(sb,obs)
                case '18gaming-diamond-luxe':
                        return slots.EighteenGaming.DiamondLuxe(sb,obs)
                case '18gaming-ketchup-vs-mayo':
                        return slots.EighteenGaming.KetchupVsMayo(sb,obs)
                case '18gaming-legends-of-olympus':
                        return slots.EighteenGaming.LegendsOfOlympus(sb,obs)
                case '18gaming-phoenix-winter-parade':
                        return slots.EighteenGaming.PhoenixWinterParade(sb,obs)
                case '18gaming-fruit-burst-bonanza':
                        return slots.EighteenGaming.FruitBurstBonanza(sb,obs)
                case '18gaming-broccoli-bankers-blitz':
                        return slots.EighteenGaming.BroccoliBankersBlitz(sb,obs)
                case '18gaming-jurassic-jungle':
                        return slots.EighteenGaming.JurassicJungle(sb,obs)
                case '18gaming-eat-sleep-rave-repeat':
                        return slots.EighteenGaming.EatSleepRaveRepeat(sb,obs)
                case '18gaming-galaxy-of-gems':
                        return slots.EighteenGaming.GalaxyOfGems(sb,obs)
                case '18gaming-egyptian-gold-reels':
                        return slots.EighteenGaming.EgyptianGoldReels(sb,obs)
                case '18gaming-zombie-harvest':
                        return slots.EighteenGaming.ZombieHarvest(sb,obs)
                case '18gaming-halloween-trick-and-spin':
                        return slots.EighteenGaming.HalloweenTrickAndSpin(sb,obs)
                case '18gaming-velvet-royale':
                        return slots.EighteenGaming.VelvetRoyale(sb,obs)
                case '18gaming-toppings-tantalizer':
                        return slots.EighteenGaming.ToppingsTantalizer(sb,obs)
                case _:
                        print('no subclass found')