import classes.slots as slots

def findSubclass(sb, slotName, obs, override=False):
        if override:
                slotName = override
        match slotName:
                case '0xedge-wild-zeus':
                        return slots.ZeroxEdge.WildZeus.WildZeus(sb,obs)
                case '0xedgefrutti-bonanza':
                        return slots.ZeroxEdge.FruttiBonanza.FruttiBonanza(sb,obs)
                case '0xedge-super-candy-drop':
                        return slots.ZeroxEdge.SuperCandyDrop.SuperCandyDrop(sb,obs)
                case '0xedge-do-not-redeem-it':
                        return slots.ZeroxEdge.DoNotRedeemIt.DoNotRedeemIt(sb,obs)
                case '0xedge-5-alpha-planets':
                        return slots.ZeroxEdge.FiveAlphaPlanets.FiveAlphaPlanets(sb,obs)
                case '0xluckylab-obsidian-spin':
                        return slots.ZeroxLuckyLab.ObsidianSpin.ObsidianSpin(sb,obs)
                case '1000lakesstudios-toivo':
                        return slots.OneThousandLakesStudios.Toivo.Toivo(sb,obs)
                case '1000lakesstudios-disco-cubes':
                        return slots.OneThousandLakesStudios.DiscoCubes.DiscoCubes(sb,obs)
                case '1000lakesstudios-bass-fury':
                        return slots.OneThousandLakesStudios.BassFury.BassFury(sb,obs)
                case '1000lakesstudios-operation-epic-taco':
                        return slots.OneThousandLakesStudios.OperationEpicTaco.OperationEpicTaco(sb,obs)
                case '1000lakesstudios-r-i-p-1000':
                        return slots.OneThousandLakesStudios.RIPOneThousand.RIPOneThousand(sb,obs)
                case '1000lakesstudios-flying-finns-1000':
                        return slots.OneThousandLakesStudios.FlyingFinsOneThousand.FlyingFinsOneThousand(sb,obs)
                case '1000lakesstudios-bloom-em':
                        return slots.OneThousandLakesStudios.BloomEm.BloomEm(sb,obs)
                case '1000lakesstudios-apex-syndicate':
                        return slots.OneThousandLakesStudios.ApexSyndicate.ApexSyndicate(sb,obs)
                case '1000lakesstudios-yakuza-v-i-p':
                        return slots.OneThousandLakesStudios.YakuzaVIP.YakuzaVIP(sb,obs)
                case '1000lakesstudios-candy-carnival-spring-spritz':
                        return slots.OneThousandLakesStudios.CandyCarnivalSpringSpritz.CandyCarnivalSpringSpritz(sb,obs)
                case '1000lakesstudios-twisted-candy-shop':
                        return slots.OneThousandLakesStudios.TwistedCandyShop.TwistedCandyShop(sb,obs)
                case '1000lakesstudios-arctic-runes':
                        return slots.OneThousandLakesStudios.ArcticRunes.ArcticRunes(sb,obs)
                case '1000lakes-rotation-of-ra':
                        return slots.OneThousandLakes.RotationOfRa.RotationOfRa(sb,obs)
                case '111lightproductions-the-syndicate':
                        return slots.OneHundredElevenLightProductions.TheSyndicate.TheSyndicate(sb,obs)
                case '111lightproductions-gemburst-rush':
                        return slots.OneHundredElevenLightProductions.GemburstRush.GemburstRush(sb,obs)
                case '111lightproductions-nfl-touchdown':
                        return slots.OneHundredElevenLightProductions.NFLTouchdown.NFLTouchdown(sb,obs)
                case '111lightproductions-dragon-fortunes':
                        return slots.OneHundredElevenLightProductions.DragonFortunes.DragonFortunes(sb,obs)
                case '111lightproductions-legends-of-the-lost-grove':
                        return slots.OneHundredElevenLightProductions.LegendsOfTheLostGrove.LegendsOfTheLostGrove(sb,obs)
                case '111lightproductions-hearts-in-sync':
                        return slots.OneHundredElevenLightProductions.HeartsInSync.HeartsInSync(sb,obs)
                case '111lightproductions-sunset-serenade':
                        return slots.OneHundredElevenLightProductions.SunsetSerenade.SunsetSerenade(sb,obs)
                case '1789studios-cat-war':
                        return slots.OneThousandSevenHundredEightyNineStudios.CatWar.CatWar(sb,obs)
                case '18gaming-sweet-stake-25k':
                        return slots.EighteenGaming.SweetStakeTwentyFiveK.SweetStakeTwentyFiveK(sb,obs)
                case '18gaming-bowling-riches':
                        return slots.EighteenGaming.BowlingRiches.BowlingRiches(sb,obs)
                case '18gaming-golden-piggy':
                        return slots.EighteenGaming.GoldenPiggy.GoldenPiggy(sb,obs)
                case '18gaming-rock-n-roll':
                        return slots.EighteenGaming.RockNRoll.RockNRoll(sb,obs)
                case '18gaming-buffalo-blaze-2':
                        return slots.EighteenGaming.BuffaloBlazeTwo.BuffaloBlazeTwo(sb,obs)
                case '18gaming-mystical-plum-grove':
                        return slots.EighteenGaming.MysticalPlumGrove.MysticalPlumGrove(sb,obs)
                case '18gaming-aztec-sun-blaze':
                        return slots.EighteenGaming.AztecSunBlaze.AztecSunBlaze(sb,obs)
                case '18gaming-wrath-of-olympus':
                        return slots.EighteenGaming.WrathOfOlympus.WrathOfOlympus(sb,obs)
                case '18gaming-crypto-bonanza':
                        return slots.EighteenGaming.CryptoBonanza.CryptoBonanza(sb,obs)
                case '18gaming-dragon-fortune':
                        return slots.EighteenGaming.DragonFortune.DragonFortune(sb,obs)
                case '18gaming-sheriffs-bounty':
                        return slots.EighteenGaming.SheriffsBounty.SheriffsBounty(sb,obs)
                case '18gaming-wall-street-honey-stakes':
                        return slots.EighteenGaming.WallStreetHoneyStakes.WallStreetHoneyStakes(sb,obs)
                case '18gaming-buffalo-blaze':
                        return slots.EighteenGaming.BuffaloBlaze.BuffaloBlaze(sb,obs)
                case '18gaming-derby-race':
                        return slots.EighteenGaming.DerbyRace.DerbyRace(sb,obs)
                case '18gaming-beachside-betties':
                        return slots.EighteenGaming.BeachsideBetties.BeachsideBetties(sb,obs)
                case '18gaming-diamond-luxe':
                        return slots.EighteenGaming.DiamondLuxe.DiamondLuxe(sb,obs)
                case '18gaming-ketchup-vs-mayo':
                        return slots.EighteenGaming.KetchupVsMayo.KetchupVsMayo(sb,obs)
                case '18gaming-legends-of-olympus':
                        return slots.EighteenGaming.LegendsOfOlympus.LegendsOfOlympus(sb,obs)
                case '18gaming-phoenix-winter-parade':
                        return slots.EighteenGaming.PhoenixWinterParade.PhoenixWinterParade(sb,obs)
                case '18gaming-fruit-burst-bonanza':
                        return slots.EighteenGaming.FruitBurstBonanza.FruitBurstBonanza(sb,obs)
                case '18gaming-broccoli-bankers-blitz':
                        return slots.EighteenGaming.BroccoliBankersBlitz.BroccoliBankersBlitz(sb,obs)
                case '18gaming-jurassic-jungle':
                        return slots.EighteenGaming.JurassicJungle.JurassicJungle(sb,obs)
                case '18gaming-eat-sleep-rave-repeat':
                        return slots.EighteenGaming.EatSleepRaveRepeat.EatSleepRaveRepeat(sb,obs)
                case '18gaming-galaxy-of-gems':
                        return slots.EighteenGaming.GalaxyOfGems.GalaxyOfGems(sb,obs)
                case '18gaming-egyptian-gold-reels':
                        return slots.EighteenGaming.EgyptianGoldReels.EgyptianGoldReels(sb,obs)
                case '18gaming-zombie-harvest':
                        return slots.EighteenGaming.ZombieHarvest.ZombieHarvest(sb,obs)
                case '18gaming-halloween-trick-and-spin':
                        return slots.EighteenGaming.HalloweenTrickAndSpin.HalloweenTrickAndSpin(sb,obs)
                case '18gaming-velvet-royale':
                        return slots.EighteenGaming.VelvetRoyale.VelvetRoyale(sb,obs)
                case '18gaming-toppings-tantalizer':
                        return slots.EighteenGaming.ToppingsTantalizer.ToppingsTantalizer(sb,obs)
                case '18gaming-sushi-jet-dash':
                        return slots.EighteenGaming.SushiJetDash.SushiJetDash(sb,obs)
                case '18gaming-the-great-potato-war':
                        return slots.EighteenGaming.TheGreatPotatoWar.TheGreatPotatoWar(sb,obs)
                case '18gaming-emojis-day-out':
                        return slots.EighteenGaming.EmojisDayOut.EmojisDayOut(sb,obs)
                case '18gaming-grand-prix-fortunes':
                        return slots.EighteenGaming.GrandPrixFortunes.GrandPrixFortunes(sb,obs)
                case '18gaming-meme-clash':
                        return slots.EighteenGaming.MemeClash.MemeClash(sb,obs)
                case '18gaming-street-of-spices':
                        return slots.EighteenGaming.StreetOfSpices.StreetOfSpices(sb,obs)
                case '18gaming-sloth-rush':
                        return slots.EighteenGaming.SlothRush.SlothRush(sb,obs)
                case '18gaming-kill-the-bill':
                        return slots.EighteenGaming.KillTheBill.KillTheBill(sb,obs)
                case '18gaming-pistachio-paradise':
                        return slots.EighteenGaming.PistachioParadise.PistachioParadise(sb,obs)
                case _:
                        print('no subclass found')