from . import AztecSunBlaze
from . import BeachsideBetties
from . import BowlingRiches
from . import BroccoliBankersBlitz
from . import BuffaloBlaze
from . import BuffaloBlazeTwo
from . import CryptoBonanza
from . import DerbyRace
from . import DiamondLuxe
from . import DragonFortune
from . import EatSleepRaveRepeat
from . import EgyptianGoldReels
from . import FruitBurstBonanza
from . import GalaxyOfGems
from . import GoldenPiggy
from . import HalloweenTrickAndSpin
from . import JurassicJungle
from . import KetchupVsMayo
from . import LegendsOfOlympus
from . import LuckyJoker
from . import MysticalPlumGrove
from . import PhoenixWinterParade
from . import RockNRoll
from . import SantasChristmasMagic
from . import SheriffsBounty
from . import SweetStakeTwentyFiveK
from . import ToppingsTantalizer
from . import VelvetRoyale
from . import WallStreetHoneyStakes
from . import WrathOfOlympus
from . import ZombieHarvest
from . import SushiJetDash
from . import TheGreatPotatoWar
from . import EmojisDayOut
from . import GrandPrixFortunes
from . import MemeClash
from . import StreetOfSpices
from . import SlothRush
from . import KillTheBill
from . import PistachioParadise